(function(g){var window=this;var Nua=function(a,b){var c=[];g.om(b,function(a){var b;try{b=g.WD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.VD(b)&&c.push(a):c.push(a)},a);
return c},Oua=function(a,b){var c=Nua(a,b);
(0,g.F)(c,function(a){g.WD.prototype.remove.call(this,a)},a)},s9=function(a,b){g.wW.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.W=a;this.B=!1;this.G={};this.V(a,"onMdxReceiversChange",this.H);this.V(a,"presentingplayerstatechange",this.H);this.H()},Pua=function(a){return a.H?a.F+((0,g.E)()-a.A)/1E3:a.F},Qua=function(){var a=g.xH;
Oua(a,a.g.Od(!0))},t9=function(a){g.$H.call(this,"ScreenServiceProxy");
this.Vc=a;this.o=[];this.o.push(this.Vc.$_s("screenChange",(0,g.z)(this.cQ,this)));this.o.push(this.Vc.$_s("onlineScreenChange",(0,g.z)(this.yM,this)))},u9=function(a){g.NH("cloudview",a)},Rua=function(a){u9("setApiReady_ "+a);
g.oa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},v9=function(){return g.u("yt.mdx.remote.cloudview.instance_")},Sua=function(a){g.RG[a]&&(a=g.RG[a],(0,g.F)(a,function(a){g.PG[a]&&delete g.PG[a]}),a.length=0)},w9=function(){return g.u("yt.mdx.remote.connection_")},x9=function(a){g.oa("yt.mdx.remote.connectData_",a,void 0)},Tua=function(a){g.oa("yt.mdx.remote.currentScreenId_",a,void 0)},y9=function(){return g.u("yt.mdx.remote.currentScreenId_")},A9=function(){if(!z9){var a=g.u("yt.mdx.remote.screenService_");
z9=a?new t9(a):null}return z9},B9=function(a){g.oa("yt.mdx.remote.cloudview.initializing_",a,void 0)},C9=function(){return!!g.u("yt.mdx.remote.cloudview.apiReady_")},D9=function(a){u9("setCastInstalled_ "+a);
g.zH("yt-remote-cast-installed",a)},E9=function(a){g.NH("cloudview",a)},Uua=function(a,b){v9().init(a,b)},F9=function(){return!!g.AH("yt-remote-cast-installed")},Vua=function(){u9("dispose");
var a=v9();a&&a.dispose();g.oa("yt.mdx.remote.cloudview.instance_",null,void 0);Rua(!1);(0,g.n2)(G9);G9.length=0},Wua=function(){var a=window.document.createElement("a");
g.Rd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ta(a)},Xua=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Yua=function(a){var b=g.OG();
if(b)if(b.clear(a),a)Sua(a);else for(var c in g.RG)Sua(c)},H9=function(){return g.u("yt.mdx.remote.channelParams_")||{}},J9=function(a){var b=w9();
x9(null);a||Tua("");g.oa("yt.mdx.remote.connection_",a,void 0);I9&&((0,g.F)(I9,function(b){b(a)}),I9.length=0);
b&&!a?g.WG("yt-remote-connection-change",!1):!b&&a&&g.WG("yt-remote-connection-change",!0)},Zua=function(){return g.u("yt.mdx.remote.connectData_")},K9=function(){var a=y9();
if(!a)return null;var b=A9().Td();return g.ZH(b,a)},$ua=function(a,b){D9(!0);
B9(!1);Uua(a,function(a){a?(Rua(!0),g.VG("yt-remote-cast2-api-ready")):(E9("Failed to initialize cast API."),D9(!1),g.BH("yt-remote-cast-available"),g.BH("yt-remote-cast-receiver"),Vua());b(a)})},ava=function(){return F9()?v9()?v9().getCastSession():(E9("getCastSelector: Cast is not initialized."),null):(E9("getCastSelector: Cast API is not installed!"),null)},bva=function(){var a=Wua(),b=window.document.getElementById(a),c=b&&g.NF(b,"loaded");
c||b&&!c||(b=Xua(a,function(){g.NF(b,"loaded")||(g.OF(b,"loaded","true"),g.VG(a),g.gF(g.za(Yua,a),0))}))},cva=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},dva=function(){if(g.noa){var a=2,b=g.Fh(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Kh("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Hh,c)}},M9=function(a,b){y9();
K9()&&K9();Tua(a.id);var c=new g.dJ(L9,a,H9());c.connect(b,Zua());c.subscribe("beforeDisconnect",function(a){g.WG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){w9()&&(w9(),J9(null))});
J9(c)},N9=function(){var a=g.eI();
if(!a)return null;var b=A9().Td();return g.ZH(b,a)},O9=function(a){g.NH("remote",a)},P9=function(){var a=w9();
return!!a&&3!=a.getProxyState()},Q9=function(){C9()?v9().stopSession():E9("stopSession called before API ready.");
var a=w9();a&&(a.disconnect(1),J9(null))},eva=function(){var a;
a=A9().Vc.$_gos();var b=K9();b&&w9()&&(g.YH(a,b)||a.push(b));return cva(a)},S9=function(a,b){g.qG.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.jC;this.A=this.o=null;this.H=(0,g.z)(this.JK,this);this.F=(0,g.z)(this.Ck,this);this.G=(0,g.z)(this.IK,this);this.J=(0,g.z)(this.WK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.qt,this),fva(this))):c=3;0!=c&&(b?this.qt(c):g.gF((0,g.z)(function(){this.qt(c)},this),0));
var d=ava();d&&R9(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},T9=function(a){return new g.TI(a.B.getPlayerContextData())},gva=function(a,b,c,d,e){var f=T9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.XI(f,b,d);g.t(c)&&(g.VI(f,c),l.currentTime=c);g.t(k)&&(l.listId=k);U9(a,"setPlaylist",l);e||V9(a,f)},fva=function(a){(0,g.F)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.za(this.SM,a),this))},a)},hva=function(a){(0,g.F)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},W9=function(a,b){50>a.C.Dc()&&g.lC(a.C,b)},X9=function(a,b,c){var d=T9(a);
g.VI(d,c);-1E3!=d.g&&(d.g=b);V9(a,d)},U9=function(a,b,c){a.B.sendMessage(b,c)},V9=function(a,b){hva(a);
a.B.setPlayerContextData(g.YI(b));fva(a)},R9=function(a,b){a.A&&(a.A.removeUpdateListener(a.H),a.A.removeMediaListener(a.F),a.Ck(null));
a.A=b;a.A&&(Y9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.H),a.A.addMediaListener(a.F),a.A.media.length&&a.Ck(a.A.media[0]))},iva=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=T9(a);b.contentId!=d.videoId&&Y9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.VI(d,a.o.getEstimatedTime());V9(a,d)}else Y9("No cast media video. Ignoring state update.")},Y9=function(a){g.NH("CP",a)},Z9=function(a,b,c){return(0,g.z)(function(a){this.ac("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.ac("Retrying "+b+" using MDx browser channel."),U9(this,b,c))},a)},jva=function(a){var b=!1;
v9()||(a=new g.NI(a),a.subscribe("yt-remote-cast2-availability-change",function(a){g.zH("yt-remote-cast-available",a);g.WG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){u9("onReceiverSelected: "+a.friendlyName);
g.zH("yt-remote-cast-receiver",a);g.WG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){u9("onReceiverResumed: "+a.friendlyName);
g.zH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){u9("onSessionChange: "+g.VH(a));
a||g.BH("yt-remote-cast-receiver");g.WG("yt-remote-cast2-session-change",a)}),g.oa("yt.mdx.remote.cloudview.instance_",a,void 0),b=!0);
u9("cloudview.createSingleton_: "+b);return b},kva=function(){var a=0<=g.Gb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.FG||a},$9=function(a,b){C9()?v9().setConnectedScreenStatus(a,b):E9("setConnectedScreenStatus called before ready.")},lva=function(){u9("clearCurrentReceiver");
g.BH("yt-remote-cast-receiver")},mva=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){dva();a({command:"cast.sender.init"});return}}if(window.chrome)if(dva(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.Dh();55<=b?a="55":50<=b&&(a="50");g.Kh("//www.gstatic.com/eureka/clank"+a+g.Ih,g.Hh)}else g.Lh(0);else g.Hh()},nva=function(a){a?(g.zH("yt-remote-session-app",a.app),g.zH("yt-remote-session-name",a.name)):(g.BH("yt-remote-session-app"),g.BH("yt-remote-session-name"));
g.oa("yt.mdx.remote.channelParams_",a,void 0)},ova=function(){var a=H9();
if(g.Ub(a)){var a=g.dI(),b=g.AH("yt-remote-session-name")||"",c=g.AH("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.oa("yt.mdx.remote.channelParams_",a,void 0)}},pva=function(){var a=N9();
a?(O9("Resume connection to: "+g.VH(a)),M9(a,0)):(g.mI(),lva(),O9("Skipping connecting because no session screen found."))},qva=function(a){O9("remote.onCastSessionChange_: "+g.VH(a));
if(a){var b=K9();b&&b.id==a.id?$9(b.id,"YouTube TV"):(b&&Q9(),M9(a,1))}else w9()&&Q9()},rva=function(){var a=eva(),b=K9();
b||(b=N9());return g.ab(a,function(a){return b&&g.SH(b,a.key)?!0:!1})},sva=function(){var a=g.AH("yt-remote-cast-receiver");
return a?a.friendlyName:null},tva=function(a,b,c,d){kva()?jva(b)&&(B9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?$ua(a,c):(window.__onGCastApiAvailable=function(b,d){b?$ua(a,c):(E9("Failed to load cast API: "+d),D9(!1),B9(!1),g.BH("yt-remote-cast-available"),g.BH("yt-remote-cast-receiver"),Vua(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):bva():mva())):u9("Cannot initialize because not running Chrome")},
uva=function(a){this.port=this.A="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.yg(a)||"";b&&(this.port=":"+b);this.A=g.xg(a)||"";a=g.Gb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Sa(a,"10.0")&&(this.o=!1))},a$=function(a){g.X.call(this,{K:"div",
X:"ytp-remote",R:[{K:"div",X:"ytp-remote-display-status",R:[{K:"div",X:"ytp-remote-display-status-icon",R:[g.CE()]},{K:"div",X:"ytp-remote-display-status-text",R:["{{statustext}}"]},{K:"div",X:"ytp-remote-display-status-receiver",R:["{{receiver}}"]}]}]});this.g=new g.XV(this,250);g.M(this,this.g);this.A=a;this.V(a,"presentingplayerstatechange",this.B);vva(this,g.vV(a))},vva=function(a,b){if(3==a.A.Xa()){var c;
c=g.V(b,128)?g.U("YTP_MDX_STATUS_ERROR"):b.qb()||g.V(b,4)?g.U("YTP_MDX_STATUS_PLAYING"):g.U("YTP_MDX_STATUS_CONNECTED");var d=a.A.Xc("remote","currentReceiver");a.update({statustext:c,receiver:d.name});a.g.show()}else g.ZV(a.g)},b$=function(a,b,c){g.L.call(this);
this.H=a;this.W=b;b.addEventListener("onVolumeChange",this.yn,this);b.addEventListener("onCaptionsTrackListChanged",this.iz,this);b.addEventListener("captionschanged",this.Vy,this);b.addEventListener("captionssettingschanged",this.Cs,this);b.addEventListener("videoplayerreset",this.Fk,this);b.addEventListener("mdxautoplaycancel",this.Uu,this);this.C=!1;this.g=c;c.subscribe("proxyStateChange",this.xz,this);c.subscribe("remotePlayerChange",this.Ek,this);c.subscribe("remoteQueueChange",this.Fk,this);
c.subscribe("autoplayUpNext",this.Ty,this);c.subscribe("previousNextChange",this.uz,this);c.subscribe("nowAutoplaying",this.lz,this);c.subscribe("autoplayDismissed",this.Sy,this);this.suggestion=null;this.D=new g.gK(64);this.o=new g.lu(this.FA,500,this);g.M(this,this.o);this.A=new g.lu(this.GA,1E3,this);g.M(this,this.A);this.B={};this.G=new g.lu(this.UA,1E3,this);g.M(this,this.G);this.F=new g.tk(this.XR,1E3,this);g.M(this,this.F);this.J=g.x;this.Cs();this.Fk();this.Ek()},c$=function(a,b){var c=a.H,
d=a.W.getVideoData().lengthSeconds;
c.H=b||0;c.g.U("progresssync",b,d)},wva=function(a){c$(a,0);
a.o.stop();d$(a,new g.gK(64))},g$=function(a,b){if(e$(a)&&!a.C){var c=null;
b&&(c={style:a.W.il()},g.ac(c,b));a.g.zA(f$(a),c);a.B=T9(a.g).o}},h$=function(a,b){var c=a.W.df();
c?gva(a.g,f$(a),b,c.Rd(),c.listId.toString()):gva(a.g,f$(a),b);d$(a,new g.gK(1))},xva=function(a,b){if(b){var c=a.W.Xc("captions","tracklist",{ox:1});
c&&c.length?(a.W.Ge("captions","track",b),a.C=!1):(a.W.al("captions"),a.C=!0)}else a.W.Ge("captions","track",{})},e$=function(a){return T9(a.g).videoId==f$(a)},f$=function(a){return a.W.getVideoData().videoId},d$=function(a,b){a.A.stop();
var c=a.D;if(b.o!=c.o||b.g!=c.g){var d=g.V(b,2);if(d!=g.V(a.D,2)){var e=a.W;(e=g.uV(e.app,e.playerType||1))&&g.sU(e,d)}a.D=b;yva(a.H,c,b)}},i$=function(){var a=rva();
!a&&F9()&&sva()&&(a={key:"cast-selector-receiver",name:sva()});return a},zva=function(){var a=eva();
F9()&&g.AH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Ava=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.xH&&Qua();g.gI();L9||(L9=new uva,g.oI()&&(L9.g="/api/loungedev"));I9||(I9=g.u("yt.mdx.remote.deferredProxies_")||[],g.oa("yt.mdx.remote.deferredProxies_",I9,void 0));ova();var c=A9();if(!c){var d=new g.zI(L9);g.oa("yt.mdx.remote.screenService_",d,void 0);c=A9();tva(a,d,function(a){a?y9()&&$9(y9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.WG("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript))}b&&!g.u("yt.mdx.remote.initialized_")&&
(g.oa("yt.mdx.remote.initialized_",!0,void 0),O9("Initializing: "+g.Mc(b)),j$.push(g.SG("yt-remote-cast2-availability-change",function(){g.WG("yt-remote-receiver-availability-change")})),j$.push(g.SG("yt-remote-cast2-receiver-selected",function(){x9(null);
g.WG("yt-remote-auto-connect","cast-selector-receiver")})),j$.push(g.SG("yt-remote-cast2-receiver-resumed",function(){g.WG("yt-remote-receiver-resumed","cast-selector-receiver")})),j$.push(g.SG("yt-remote-cast2-session-change",qva)),j$.push(g.SG("yt-remote-connection-change",function(a){a?$9(y9(),"YouTube TV"):N9()||($9(null,null),lva())})),a=H9(),b.isAuto&&(a.id+="#dial"),g.wG("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,O9(" -- with channel params: "+g.Mc(a)),
nva(a),c.start(),y9()||pva())},k$=function(){F9()?v9()?C9()?(u9("Requesting cast selector."),v9().requestSession()):(u9("Wait for cast API to be ready to request the session."),G9.push(g.SG("yt-remote-cast2-api-ready",k$))):E9("requestCastSelector: Cast is not initialized."):E9("requestCastSelector: Cast API is not installed!")},l$=function(a){g.TV.call(this,a);
this.A={key:g.XH(),name:g.U("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.gK(64);this.H=0;var b=g.oV(a).C;b&&(b=b.A&&b.A.g)&&(b=new s9(a,b),g.M(this,b));b=new a$(a);g.M(this,b);g.NV(a,b.element,5)},yva=function(a,b,c){a.F=c;
a.g.U("presentingplayerstatechange",new g.kU(c,b))},m$=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)Q9();
else{a.B=b;var c;c=a.g.getPlaylistId();var d=a.g.getVideoData().videoId;if(c||d){var e,f=a.g.df();if(f){e=[];for(var k=0;k<f.getLength();k++)e[k]=f.Yb(k).videoId}else e=[a.g.getVideoData().videoId];c={videoIds:e,listId:c,videoId:d,index:Math.max(a.g.qB(),0),currentTime:a.g.getCurrentTime()}}else c=null;O9("Connecting to: "+g.Mc(b));"cast-selector-receiver"==b.key?(x9(c||null),c=c||null,C9()?v9().setLaunchParams(c):E9("setLaunchParams called before ready.")):!c&&P9()&&y9()==b.key?g.WG("yt-remote-connection-change",
!0):(Q9(),x9(c||null),c=A9().Td(),(c=g.ZH(c,b.key))&&M9(c,1))}};
g.p(s9,g.wW);s9.prototype.H=function(){var a=this.W.Xc("remote","receivers");a&&1<a.length&&!this.W.Xc("remote","quickCast")?(this.G=g.Cb(a,this.F,this),g.yW(this,(0,g.H)(a,this.F)),a=this.W.Xc("remote","currentReceiver"),g.xW(this,this.F(a)),this.B||(g.P1(this.g,this),this.B=!0)):this.B&&(g.Q1(this.g,this),this.B=!1)};
s9.prototype.F=function(a){return a.key};
s9.prototype.Ne=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.G[a].name};
s9.prototype.hd=function(a){g.wW.prototype.hd.call(this,a);this.W.Ge("remote","currentReceiver",this.G[a]);this.g.Vb()};
g.A(t9,g.$H);g.h=t9.prototype;g.h.Td=function(a){return this.Vc.$_gs(a)};
g.h.contains=function(a){return!!this.Vc.$_c(a)};
g.h.get=function(a){return this.Vc.$_g(a)};
g.h.start=function(){this.Vc.$_st()};
g.h.uo=function(a,b,c){this.Vc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Vc.$_r(a,b,c)};
g.h.ho=function(a,b,c,d){this.Vc.$_un(a,b,c,d)};
g.h.P=function(){for(var a=0,b=this.o.length;a<b;++a)this.Vc.$_ubk(this.o[a]);this.o.length=0;this.Vc=null;t9.O.P.call(this)};
g.h.cQ=function(){this.U("screenChange")};
g.h.yM=function(){this.U("onlineScreenChange")};
var z9=null,G9=[],I9=null,L9=null;g.A(S9,g.qG);g.h=S9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.x,Z9(this,"play")):U9(this,"play"),X9(this,1,g.WI(T9(this))),this.U("remotePlayerChange")):W9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.x,Z9(this,"pause")):U9(this,"pause"),X9(this,2,g.WI(T9(this))),this.U("remotePlayerChange")):W9(this,this.pause)};
g.h.fB=function(a){if(1==this.g){if(this.o){var b=T9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.qb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.x,Z9(this,"seekTo",{newTime:a}))}else U9(this,"seekTo",{newTime:a});X9(this,3,a);this.U("remotePlayerChange")}else W9(this,g.za(this.fB,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.x,Z9(this,"stopVideo")):U9(this,"stopVideo");var a=T9(this);a.index=-1;a.videoId="";g.UI(a);V9(this,a);this.U("remotePlayerChange")}else W9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=T9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){Y9("set receiver volume: "+d)},this),(0,g.z)(function(){this.ac("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){Y9("set receiver muted: "+b)},this),(0,g.z)(function(){this.ac("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);U9(this,"setVolume",e)}c.muted=b;c.volume=a;V9(this,c)}else W9(this,g.za(this.setVolume,a,b))};
g.h.zA=function(a,b){if(1==this.g){var c=T9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Mc(b.style),g.ac(d,c.o));U9(this,"setSubtitlesTrack",d);V9(this,c)}else W9(this,g.za(this.zA,a,b))};
g.h.lt=function(a,b){if(1==this.g){U9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Lc.id});var c=T9(this);c.audioTrackId=b.Lc.id;V9(this,c)}else W9(this,g.za(this.lt,a,b))};
g.h.eB=function(a,b){if(1==this.g){if(a&&b){var c=T9(this);g.XI(c,a,b);V9(this,c)}U9(this,"previous")}else W9(this,g.za(this.eB,a,b))};
g.h.dB=function(a,b){if(1==this.g){if(a&&b){var c=T9(this);g.XI(c,a,b);V9(this,c)}U9(this,"next")}else W9(this,g.za(this.dB,a,b))};
g.h.Jv=function(){1==this.g?U9(this,"dismissAutoplay"):W9(this,this.Jv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}S9.O.dispose.call(this)};
g.h.P=function(){hva(this);this.B=null;this.C.clear();R9(this,null);S9.O.P.call(this)};
g.h.qt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.mC(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.SM=function(a,b){this.U(a,b)};
g.h.JK=function(a){if(!a)this.Ck(null),R9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=T9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)Y9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,V9(this,b)}};
g.h.Ck=function(a){Y9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),iva(this),this.U("remotePlayerChange")};
g.h.IK=function(a){a?(iva(this),this.U("remotePlayerChange")):this.Ck(null)};
g.h.WK=function(){var a=ava();a&&R9(this,a)};
g.h.ac=function(a){g.NH("CP",a)};
var j$=[];g.h=uva.prototype;g.h.Fh=function(a,b,c){var d=this.g;if(g.t(c)?c:this.o)d="https://"+this.A+this.port+this.g;return g.Gg(d+a,b||{})};
g.h.kt=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Jb:g.za(this.XP,c,!0),onError:g.za(this.WP,d),gd:g.za(this.YP,d)};b&&(c.Ob=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.tF(a,c)};
g.h.XP=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.WP=function(a,b){a(Error("Request error: "+b.status))};
g.h.YP=function(a){a(Error("request timed out"))};
g.p(a$,g.X);a$.prototype.B=function(a){vva(this,a.state)};
g.A(b$,g.L);g.h=b$.prototype;
g.h.P=function(){b$.O.P.call(this);this.o.stop();this.A.stop();this.J();this.W.removeEventListener("onVolumeChange",this.yn,this);this.W.removeEventListener("onCaptionsTrackListChanged",this.iz,this);this.W.removeEventListener("captionschanged",this.Vy,this);this.W.removeEventListener("videoplayerreset",this.Fk,this);this.W.removeEventListener("captionssettingschanged",this.Cs,this);this.W.removeEventListener("mdxautoplaycancel",this.Uu,this);this.g.unsubscribe("proxyStateChange",this.xz,this);this.g.unsubscribe("remotePlayerChange",
this.Ek,this);this.g.unsubscribe("remoteQueueChange",this.Fk,this);this.g.unsubscribe("autoplayUpNext",this.Ty,this);this.g.unsubscribe("previousNextChange",this.uz,this);this.g.unsubscribe("nowAutoplaying",this.lz,this);this.g.unsubscribe("autoplayDismissed",this.Sy,this);this.g=this.H=null};
g.h.TB=function(a,b){2==this.g.g||(e$(this)?this.zG.apply(this,arguments):this.vG.apply(this,arguments))};
g.h.Vy=function(a){this.TB("control_subtitles_set_track",g.Ub(a)?null:a)};
g.h.Cs=function(){var a=this.W.Xc("captions","track");g.Ub(a)||g$(this,a)};
g.h.vG=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":h$(this,this.W.getCurrentTime());break;case "control_seek":h$(this,c[0]);break;case "control_subtitles_set_track":g$(this,c[0]);break;case "control_set_audio_track":c=c[0],e$(this)&&this.g.lt(f$(this),c)}};
g.h.zG=function(a,b){if(1081!=T9(this.g).g||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":T9(this.g).qb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.F.Li(c[0],c[1]);break;case "control_subtitles_set_track":g$(this,c[0]);break;case "control_set_audio_track":c=c[0],e$(this)&&this.g.lt(f$(this),c)}}};
g.h.yn=function(a){if(e$(this)){this.g.unsubscribe("remotePlayerChange",this.Ek,this);var b=Math.round(a.volume);a=!!a.muted;var c=T9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.G.start();this.g.subscribe("remotePlayerChange",this.Ek,this)}};
g.h.iz=function(){g.Ub(this.B)||xva(this,this.B);this.C=!1};
g.h.xz=function(a,b){this.A.stop();2==b&&this.GA()};
g.h.Ek=function(){if(e$(this)){this.o.stop();var a=T9(this.g);switch(a.g){case 1081:d$(this,new g.gK(8));break;case 1:this.FA();d$(this,new g.gK(8));break;case 1083:case 3:d$(this,new g.gK(9));break;case 0:d$(this,new g.gK(2));this.F.stop();c$(this,this.W.getVideoData().lengthSeconds);break;case 1082:d$(this,new g.gK(4));break;case 2:d$(this,new g.gK(4));c$(this,g.WI(a));break;case -1:d$(this,new g.gK(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},d$(this,
new g.gK(128,a))}var a=T9(this.g).o,b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.B=a,xva(this,a));a=T9(this.g);-1==a.volume||Math.round(this.W.getVolume())==a.volume&&this.W.ae()==a.muted||this.G.isActive()||this.UA()}else wva(this)};
g.h.uz=function(){this.W.U("mdxpreviousnextchange")};
g.h.Fk=function(){e$(this)||wva(this)};
g.h.Uu=function(){this.g.Jv()};
g.h.Ty=function(a){a&&(a=g.tF("/watch_queue_ajax",{method:"GET",Hc:{action_get_watch_queue_item:1,video_id:a},Jb:(0,g.z)(this.QN,this)}))&&(this.J=(0,g.z)(a.abort,a))};
g.h.QN=function(a,b){var c=new g.NQ({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.W.U("mdxautoplayupnext",c)};
g.h.lz=function(a){(0,window.isNaN)(a)||this.W.U("mdxnowautoplaying",a)};
g.h.Sy=function(){this.W.U("mdxautoplaycanceled")};
g.h.XR=function(a,b){-1==T9(this.g).g?h$(this,a):b&&this.g.fB(a)};
g.h.UA=function(){if(e$(this)){var a=T9(this.g);this.W.removeEventListener("onVolumeChange",this.yn,this);a.muted?this.W.mute():this.W.yg();this.W.setVolume(a.volume);this.W.addEventListener("onVolumeChange",this.yn,this)}};
g.h.FA=function(){this.o.stop();if(!this.g.la()){var a=T9(this.g);a.qb()&&d$(this,new g.gK(8));c$(this,g.WI(a));this.o.start()}};
g.h.GA=function(){this.A.stop();this.o.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.A.start()};
g.A(l$,g.TV);g.h=l$.prototype;g.h.create=function(){Ava("embedded"==g.Y(this.g).g);this.D.push(g.SG("yt-remote-before-disconnect",this.FK,this));this.D.push(g.SG("yt-remote-connection-change",this.bN,this));this.D.push(g.SG("yt-remote-receiver-availability-change",this.vz,this));this.D.push(g.SG("yt-remote-auto-connect",this.ZM,this));this.D.push(g.SG("yt-remote-receiver-resumed",this.YM,this));this.vz()};
g.h.load=function(){this.g.Ep();l$.O.load.call(this);this.C=new b$(this,this.g,this.o);var a;a=(a=Zua())?a.currentTime:0;var b=P9()?new S9(w9(),void 0):null;0==a&&b&&(a=g.WI(T9(b)));0!=a&&(this.H=a||0,this.g.U("progresssync",a,void 0));yva(this,this.F,this.F);g.O2(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.B=this.A;g.Ve(this.C,this.o);this.o=this.C=null;l$.O.unload.call(this);g.O2(this.g.app,5)};
g.h.P=function(){(0,g.n2)(this.D);l$.O.P.call(this)};
g.h.nl=function(a,b){this.loaded&&this.C.TB.apply(this.C,arguments)};
g.h.aG=function(){return this.loaded?this.C.suggestion:null};
g.h.Cf=function(){return this.o?T9(this.o).Cf:!1};
g.h.hasNext=function(){return this.o?T9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.CR=function(){var a=T9(this.o),b=this.g.getVideoData(),c=this.g.Ed(),d=b.clipEnd,b=b.clipStart,e=this.getCurrentTime(),f=a.getDuration(),k;k=a.H?a.B+((0,g.E)()-a.A)/1E3:a.B;var l=1>=Pua(a)-this.getCurrentTime(),m=a.J,n=Pua(a),a=0<a.C?a.C+((0,g.E)()-a.A)/1E3:a.C;return{allowSeeking:c,clipEnd:d,clipStart:b,current:e,displayedStart:-1,duration:f,ingestionTime:k,isPeggedToLive:l,loaded:m,seekableEnd:n,seekableStart:a}};
g.h.DR=function(){this.o&&this.o.dB()};
g.h.ER=function(){this.o&&this.o.eB()};
g.h.FK=function(a){1==a&&(this.J=this.o?T9(this.o):null)};
g.h.bN=function(){var a=P9()?new S9(w9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Ue(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.Rc(g.WI(a)));this.g.U("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.vz=function(){this.G=[this.A].concat(zva());var a=i$()||this.A;m$(this,a);this.g.xa("onMdxReceiversChange")};
g.h.ZM=function(){var a=i$();m$(this,a)};
g.h.YM=function(){this.B=i$()};
g.h.AR=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?k$():m$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&k$(),!0):!1}};
g.h.FR=function(){U9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ae=function(){return!1};
window._exportCheck==g.Ba&&g.oa("ytmod.player.remote",l$,void 0);})(_yt_player);
